### PR TITLE
Update sfx_service.rb

### PR DESCRIPTION
**Pull request by redlibrarian**
Add local blacklight target to list of exclusions.

## Context

Related to #2073 

## What's New

Added blacklight SFX target to local exclusion list in sfx_service.rb

### CODE REVIEW

**Review by murny — DISMISSED** [review]
LGTM 👍  (might need to rebase as there is a merge conflict with CHANGELOG.md)

**Review by murny — APPROVED** [review]

**Comment by redlibrarian** [comment]
@murny Hi Shane - sorry to bug you with this. Can you see why the travis checks would be failing? I don't think I changed enough to have caused a problem... Thanks!

**Comment by murny** [comment]
Seems like same issues Tricia was having last week.

@pgwillia was there anything you found we can do to get around these travis failures?

**Comment by pgwillia** [comment]
```
Failures:

  1) Catalog Search User visits an SFX item result

     Failure/Error: visit 'catalog/954921333008'

     Net::ReadTimeout:

       Net::ReadTimeout

     # ./spec/features/catalog_search_spec.rb:22:in `block (3 levels) in <top (required)>'

     # ./spec/features/catalog_search_spec.rb:21:in `block (2 levels) in <top (required)>'

  2) Item has proper holding table Sfx item has proper holding table

     Failure/Error: visit '/catalog/954921333007'

     Net::ReadTimeout:

       Net::ReadTimeout

     # ./spec/features/item_holding_table_spec.rb:21:in `block (3 levels) in <top (required)>'

     # ./spec/features/item_holding_table_spec.rb:20:in `block (2 levels) in <top (required)>'

  3) Link to ill Sfx item has link to ill

     Failure/Error: visit '/catalog/954921333007'

     Net::ReadTimeout:

       Net::ReadTimeout

     # ./spec/features/item_ill_link_spec.rb:4:in `block (3 levels) in <top (required)>'

     # ./spec/features/item_ill_link_spec.rb:3:in `block (2 levels) in <top (required)>
```

This is happening for every PR right now.  It started last week.  I'm not sure why it suddenly has read time outs for SFX.  They should be coming from VCR.

**Comment by pgwillia** [comment]
> 
> 
> Seems like same issues Tricia was having last week.
> 
> @pgwillia was there anything you found we can do to get around these travis failures?

We could either turn off those tests (ick) or not make the checks mandatory (ick, ick).

**Comment by redlibrarian** [comment]
Hm, OK, thanks. Not sure what the best thing would be there...

**Comment by pgwillia** [comment]
@ConnorSheremeta was able to fix the failing tests. @redlibrarian you can rebase or merge.

**Pull request merged**
