### PR TITLE
fixing issue #856

### PR DESCRIPTION
**Pull request by astrilet**
modified css file to take effect for firefox browser only

### CODE REVIEW

**Comment by astrilet** [comment]
After fixing:
screenshot from 2016-07-20 13 08 03

**Comment by astrilet** [comment]
this also includes fix to issue #762 
screenshot from 2016-07-21 13 24 12

**Comment by astrilet** [comment]
removed collection from facet list, issue #983. Noticed that "Publication Year" appears twice (see screenshot attached) I modified one that we are generating explicitly with label "Publication Year 888"(this modification is not in the code that I checked in), another one comes form the search results. Do we need to change that? 
screenshot from 2016-07-22 14 44 27

**Comment by redlibrarian** [comment]
Merged into development - closing PR.

**Pull request closed without merging**
